---
sudo: true

addons:
  apt:
    packages:
      - docker-ce
      - python
      - realpath
      - ruby

install:
  - gem install asciidoctor mdl
  - pip install --user --upgrade pip
  - pip install --user yamllint

script:
  # Lint text-like files
  - scripts/pre-commit.sh --require-all
  # Build container w/ Docker
  - docker version
  - ./build.sh
