---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: glusterfs-csi-ss
spec:
  snapshotClassName: glusterfs-csi-snap
  source:
    name: glusterfs-csi-pv
    kind: PersistentVolumeClaim
