---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
  - name: redis
    image: redis
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/gluster"
      name: glusterfscsivol
  volumes:
  - name: glusterfscsivol
    persistentVolumeClaim:
      claimName: glusterfs-csi-pv
