---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-csi-pv
  annotations:
    storageClassName: glusterfs-csi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
